### PR TITLE
Feature/fix deleting values

### LINKED ISSUE #478: If a value exists in a vocab and you edit that vocab and delete the value it breaks.

### PR DESCRIPTION
**Pull request by straleyb**
Fixes #478

### CODE REVIEW

File: app/decorators/sets_attributes.rb [hunk 1]
```diff
@@ -2,12 +2,18 @@ class SetsAttributes < SimpleDelegator
...
     new_hash = {}
     self.attributes.each_pair do |key, value|
-      unless self.blacklisted_language_properties.include?(key.to_sym) 
+      if !self.blacklisted_language_properties.include?(key.to_sym) 
         value_array = []
         value.each_with_index do |val, index|
-          value_array << RDF::Literal(val, :language => form_params[:language][key][index]) unless form_params[:language][key].blank?
+          if !form_params[:language].nil?
+            value_array << RDF::Literal(val, :language => form_params[:language][key][index]) unless form_params[:language][key].blank?
+          else
```
Comment (wickr) [inline app/decorators/sets_attributes.rb]: Was this supposed to be empty?
